//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class users
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Boþ alanlarý doldurunuz")]
        public string username { get; set; }
        [Required(ErrorMessage = "Boþ alanlarý doldurunuz")]
        public string password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Boþ alanlarý doldurunuz")]
        [Compare("password", ErrorMessage = "Parolalar Eslesmedi")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Boþ alanlarý doldurunuz")]
        [StringLength(15,MinimumLength =4, ErrorMessage = "Çok kýsa ya da çok uzun karakter girdiniz")]
        public string name { get; set; }
        [Required(ErrorMessage = "Boþ alanlarý doldurunuz")]
        public string surname { get; set; }
    }
}
